name: Terraform Reusable Workflow

on:
  workflow_call:
    inputs:
      github-owner:
        required: true
        type: string
        default: techsoft3d
      terraform-version:
        required: false
        type: string
        default: '1.13.3'
      terraform-directory:
        required: false
        type: string
        default: 'terraform'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_github_owner: ${{ inputs.github-owner }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: Terraform Steps
        uses: ./.github/actions/terraform-steps
        env:
          TERRAFORM_DIRECTORY: ${{ inputs.terraform-directory }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
